# Generated by Django 5.2.6 on 2025-10-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_last_updated_by_task_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('redo', 'Redo'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
